In [5]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensordict import TensorDict

In [10]:
torch.sum(torch.load('../data/2_generated/1.pt', weights_only=False)['next', 'cost'], dim=0)

tensor([1285.0964])

In [7]:
torch.tensor([20.0]).reshape(1, 1)[0,-1]

tensor(20.)

In [2]:
td = torch.load('../data/2_generated/1.pt',weights_only=False)

In [3]:
def td_to_unfold_td(td):
    new_td = TensorDict({}, batch_size=(51,336))
    for key, tensor in td.items():
        if key=='next':
            new_td[key] = td_to_unfold_td(tensor)
        elif key=='params':
            new_td[key] = td_to_unfold_td(tensor.unsqueeze(-1))
        else:
            new_td[key] = tensor.unfold(dimension=0,size=336,step=336).permute(0,2,1)
    return new_td
        

In [4]:
td = td_to_unfold_td(td)
td

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([51, 336, 1]), device=cpu, dtype=torch.float32, is_shared=False),
        cost: Tensor(shape=torch.Size([51, 336, 1]), device=cpu, dtype=torch.float32, is_shared=False),
        done: Tensor(shape=torch.Size([51, 336, 1]), device=cpu, dtype=torch.bool, is_shared=False),
        is_init: Tensor(shape=torch.Size([51, 336, 1]), device=cpu, dtype=torch.bool, is_shared=False),
        next: TensorDict(
            fields={
                cost: Tensor(shape=torch.Size([51, 336, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                done: Tensor(shape=torch.Size([51, 336, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                is_init: Tensor(shape=torch.Size([51, 336, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                observation: Tensor(shape=torch.Size([51, 336, 65]), device=cpu, dtype=torch.float32, is_shared=False),
                params: TensorDict(
                    fiel

In [5]:
td['cost']

tensor([[[ 0.0000],
         [ 0.4034],
         [ 0.3103],
         ...,
         [-0.0209],
         [-0.0091],
         [ 0.3398]],

        [[ 0.0000],
         [ 0.4556],
         [ 0.3488],
         ...,
         [-0.0224],
         [ 0.0051],
         [ 0.1750]],

        [[ 0.0000],
         [ 0.2702],
         [ 0.2701],
         ...,
         [ 0.2037],
         [ 0.3049],
         [ 0.5744]],

        ...,

        [[ 0.0000],
         [ 0.5681],
         [ 0.4791],
         ...,
         [ 0.0719],
         [-0.0055],
         [ 0.2846]],

        [[ 0.0000],
         [ 0.4365],
         [ 0.4062],
         ...,
         [ 0.4241],
         [ 0.3023],
         [ 0.5073]],

        [[ 0.0000],
         [ 0.6102],
         [ 0.4493],
         ...,
         [ 0.1859],
         [ 0.0749],
         [ 0.3455]]])

In [7]:
torch.flip(torch.cumsum(td['cost'],dim=1),dims=[1]).shape

torch.Size([51, 336, 1])

In [40]:
def td_to_unfold_td(td):
    new_td = TensorDict({}, batch_size=(51,336))
    for key, tensor in td.items():
        if key=='next':
            new_td[key] = td_to_unfold_td(tensor)
        elif key=='params':
            new_td[key] = td_to_unfold_td(tensor.unsqueeze(-1))
        else:
            new_td[key] = tensor.unfold(dimension=0,size=336,step=336).permute(0,2,1)
    return new_td
td_to_unfold_td(td)[0].shape

torch.Size([336])

In [41]:
torch.tensor([0,1,2,3,4,5,6,7])[torch.tensor([1,2,3])]

tensor([1, 2, 3])

In [56]:
td['prosumption'][0:48].numpy()

array([[ 1.714],
       [ 1.374],
       [ 1.238],
       [ 0.094],
       [ 0.92 ],
       [ 0.468],
       [ 0.487],
       [ 0.088],
       [ 0.833],
       [ 0.553],
       [ 0.529],
       [ 0.043],
       [ 0.086],
       [ 0.045],
       [ 0.088],
       [ 0.094],
       [ 0.1  ],
       [ 0.004],
       [ 0.032],
       [ 1.057],
       [ 1.179],
       [-0.234],
       [-0.646],
       [-0.722],
       [-0.913],
       [-0.786],
       [-0.916],
       [-1.012],
       [-1.034],
       [-0.793],
       [-0.62 ],
       [-0.256],
       [ 0.035],
       [ 0.042],
       [ 0.122],
       [ 0.231],
       [ 0.379],
       [ 0.321],
       [ 0.262],
       [ 0.234],
       [ 0.306],
       [ 0.183],
       [ 0.24 ],
       [ 0.17 ],
       [ 0.506],
       [ 0.224],
       [ 0.088],
       [ 1.159]], dtype=float32)

In [59]:
td['soe'][330:340].numpy()

array([[1.6698443 ],
       [1.2494212 ],
       [0.72873247],
       [0.4567207 ],
       [0.29952443],
       [0.16238034],
       [0.        ],
       [0.21299982],
       [0.26120257],
       [0.34071386]], dtype=float32)

In [37]:
td['soe'][48:96]

tensor([[0.0000],
        [0.0304],
        [0.2672],
        [0.4001],
        [0.6886],
        [1.1291],
        [0.8816],
        [1.4434],
        [1.6692],
        [1.3714],
        [1.0854],
        [1.1297],
        [0.8424],
        [0.6250],
        [0.4896],
        [0.4889],
        [0.4522],
        [0.6708],
        [0.9569],
        [1.2640],
        [1.5770],
        [1.8141],
        [1.7581],
        [1.9911],
        [2.5032],
        [3.2007],
        [3.8028],
        [4.4131],
        [4.9345],
        [5.5240],
        [6.1548],
        [6.3679],
        [6.1504],
        [5.8415],
        [5.4406],
        [5.0861],
        [4.6516],
        [4.2049],
        [3.6788],
        [3.1315],
        [2.6518],
        [2.2922],
        [2.0066],
        [1.6155],
        [1.2880],
        [1.3060],
        [1.2421],
        [0.8532]])

In [6]:
td.unfold(dimension=0,size=48+32,step=48)

AttributeError: 'TensorDict' object has no attribute 'unfold'

In [10]:
x = torch.zeros(3,dtype=torch.int32)
torch.cat([torch.tensor([]),x]).to(dtype=torch.int32)

tensor([0, 0, 0], dtype=torch.int32)

In [2]:
trainer = OfflineTrainer()

In [8]:
obs = trainer.get_batch()

In [4]:
states = torch.empty(2, 48,65)

states[0] = torch.cat([torch.zeros((48 - 2, 65)),torch.ones(2,65)],dim=0)
states

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [5]:
obs

(tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.2759,  0.2759,  0.2759,  ..., -1.0120, -0.9610, 10.0000],
          [ 0.2759,  0.2759,  0.2203,  ..., -0.9610, -0.5500, 10.0000]]]),
 tensor([[[0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          [0.0000],
          

In [6]:
states = torch.empty(2, 48,65)

In [7]:
states[0]=obs
states

TypeError: can't assign a tuple to a torch.FloatTensor

In [124]:
from dataset.OfflineDataset import OfflineDataset

In [ ]:
ds = OfflineDataset(None, customer=1)

TypeError: OfflineDataset.__init__() got an unexpected keyword argument 'generated_data_path'

In [ ]:
ds[17470:17490]

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([2, 1]), device=cpu, dtype=torch.float32, is_shared=False),
        cost: Tensor(shape=torch.Size([2, 1]), device=cpu, dtype=torch.float32, is_shared=False),
        done: Tensor(shape=torch.Size([2, 1]), device=cpu, dtype=torch.bool, is_shared=False),
        is_init: Tensor(shape=torch.Size([2, 1]), device=cpu, dtype=torch.bool, is_shared=False),
        next: TensorDict(
            fields={
                cost: Tensor(shape=torch.Size([2, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                done: Tensor(shape=torch.Size([2, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                is_init: Tensor(shape=torch.Size([2, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                observation: Tensor(shape=torch.Size([2, 65]), device=cpu, dtype=torch.float32, is_shared=False),
                params: TensorDict(
                    fields={
                        battery_capacity: T

In [66]:
from dataset.OfflineDataset import OfflineDataset
import torch
from tensordict import TensorDict
from torch.utils.data import DataLoader, RandomSampler

In [ ]:
x = torch.tensor([1,2,3,4])

In [ ]:
x[0:4]

tensor([1, 2, 3, 4])

In [ ]:
from dataset.OnlineDataset import EnergyDataset

In [ ]:
ds = EnergyDataset(raw_data_path='../data/1_processed', forecast_size=12, customer=1,mode='train')

In [ ]:
len(ds)

365

In [ ]:
ds[0]['load'][0]

tensor(1.5530)

In [ ]:
ds[1]['load']

tensor([1.3540, 1.5840, 1.3780, 1.3290, 0.2890, 0.7010, 1.0310, 0.1200, 0.0800,
        0.5780, 1.0340, 0.0840, 0.1160, 0.0800, 0.7970, 1.0600, 0.2690, 0.3090,
        0.1640, 0.6310, 1.4860, 1.3660, 1.4660, 1.1910, 1.2260, 1.6280, 0.6170,
        1.1650, 1.1540, 1.1040, 0.3750, 0.1180, 0.2350, 0.4450, 1.1830, 1.1900,
        0.5550, 0.4050, 0.2620, 1.1000, 1.0120, 0.8170, 0.5260, 0.3350, 0.4020,
        0.1420, 0.1200, 1.1990, 1.9800, 2.6330, 2.0420, 1.8870, 0.7290, 1.6740,
        1.2830, 0.1310, 0.2950, 1.0500, 0.1060, 0.3500])

In [ ]:
td = TensorDict({
    'soe': torch.tensor([1,2,3,4,5,6,7,8,9,10])
})

In [ ]:
x = td.unfold(0,3,2)

In [ ]:
TensorDict({'soe':x},batch_size=4)[0:0]['soe']

tensor([], size=(0, 3), dtype=torch.int64)

In [ ]:
torch.rand(())

tensor(0.0590)

In [ ]:
td = TensorDict({
    'soe': torch.randint(0,10,(17520,1), dtype=torch.float32),
    'action': torch.randint(-1,1,(17520,1), dtype=torch.float32),
    'prosumption': torch.randint(-2,2,(17520,1), dtype=torch.float32),
    'prosumption_forecast': torch.randint(-2,2,(17520,5), dtype=torch.float32),
    'observation': torch.randint(-2,2,(17520,10), dtype=torch.float32),
    
}, batch_size=torch.Size([17520,]),
device='cpu'
)
torch.save(td, '../output/1.pt')

In [ ]:
td

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([17520, 1]), device=cpu, dtype=torch.float32, is_shared=False),
        observation: Tensor(shape=torch.Size([17520, 10]), device=cpu, dtype=torch.float32, is_shared=False),
        prosumption: Tensor(shape=torch.Size([17520, 1]), device=cpu, dtype=torch.float32, is_shared=False),
        prosumption_forecast: Tensor(shape=torch.Size([17520, 5]), device=cpu, dtype=torch.float32, is_shared=False),
        soe: Tensor(shape=torch.Size([17520, 1]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([17520]),
    device=cpu,
    is_shared=False)

In [ ]:
dataset = OfflineDataset('../output',1)
len(dataset)

5

In [ ]:
dataset[0]

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.float32, is_shared=False),
        prosumption: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.float32, is_shared=False),
        prosumption_forecast: Tensor(shape=torch.Size([2]), device=cpu, dtype=torch.float32, is_shared=False),
        soe: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.float32, is_shared=False)},
    batch_size=torch.Size([]),
    device=None,
    is_shared=False)

In [ ]:
dataloader = iter(DataLoader(dataset=td, batch_size=1, shuffle=True, collate_fn=lambda x: x))

In [ ]:
dataloader = iter(DataLoader(dataset=dataset, batch_size=1, shuffle=True))

In [ ]:
import numpy as np

In [ ]:
class OffData():
    def __init__(self, generated_data_path, batch_size, ep_len):
        self._td = torch.load(generated_data_path, weights_only=False)
        self._batch_size = batch_size
        self._ep_len = ep_len
        self._num_traj = int(td.batch_size.numel() / ep_len)

    def __len__(self):
        return self._num_traj
    
    def sample(self):
        inds = torch.randint(low=0, high=self._num_traj-1, size=(self._batch_size,))
        
        s, a, r, rtg, t = [],[],[],[],[]
        for i in inds:
            traj = self._td[i:i+self._ep_len]
            s.append(traj['observation'].unsqueeze(0))
            a.append(traj['action'].unsqueeze(0))
            # r.append(traj['next','observation'].unsqueeze(-1))
            t.append(np.arange(0,self._ep_len))
        states = torch.cat(s, dim=0)
        actions = torch.cat(a, dim=0)
        # rewards = torch.cat(r, dim=0)
        timesteps = torch.from_numpy(np.concatenate(t, axis=0))

        return states, actions, timesteps


In [ ]:
OffData('../output/1.pt', 1,48).sample()

(tensor([[[-2.,  0.,  1.,  1.,  0., -2.,  1.,  0., -2.,  0.],
          [ 1., -1.,  1.,  1., -2.,  0., -2.,  0.,  1.,  1.],
          [ 0., -1.,  0.,  0., -1.,  0., -2., -1.,  1.,  1.],
          [ 0., -2.,  0.,  0., -2., -1.,  1., -1., -2.,  1.],
          [ 0., -2., -1., -2., -2., -1.,  1., -1., -1.,  1.],
          [ 0., -2.,  0.,  0., -1., -2., -2.,  0., -1.,  0.],
          [-2., -2.,  1.,  1., -2.,  1., -1., -2.,  1., -1.],
          [-1., -1., -1., -1., -2.,  1.,  0.,  0.,  0.,  0.],
          [-2., -2., -1.,  0., -1., -1., -1.,  1., -1.,  1.],
          [ 1., -2.,  0.,  0., -1., -1., -2.,  1.,  1., -1.],
          [ 1.,  1., -2., -1.,  0.,  0., -2.,  0.,  1., -1.],
          [-1., -2., -1.,  0., -2.,  1., -1., -1., -1., -1.],
          [ 0., -1., -1., -1.,  0.,  0.,  1.,  0., -2., -1.],
          [-1.,  1.,  1., -1.,  1.,  0.,  1.,  0., -1., -2.],
          [-1., -2.,  1., -2.,  0.,  0., -1., -1.,  0., -1.],
          [ 0., -1., -2., -1., -2.,  1., -2., -2.,  0., -1.],
        